name: Publish Container

on: 
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: set version
      id: version
      run: |
        BRANCH=$(echo ${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/v(.*) \1 g")
        echo "::set-output name=version::$BRANCH"
    
    - name: set up qemu
      uses: docker/setup-qemu-action@v1
    
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: codming/emqx-docs-frontend
        flavor: |
          latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=semver,pattern={{ steps.version.outputs.version }}

    - name: login docker
      uses: docker/login-action@v1
      with:
        username: codming
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
